/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CardCreateDialog: typeof import('./src/components/CardCreateDialog.vue')['default']
    CardDetailPanel: typeof import('./src/components/CardDetailPanel.vue')['default']
    CardExtractPreview: typeof import('./src/components/CardExtractPreview.vue')['default']
    CardGraphView: typeof import('./src/components/CardGraphView.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    CardRelationDiscovery: typeof import('./src/components/CardRelationDiscovery.vue')['default']
    CardReviewMode: typeof import('./src/components/CardReviewMode.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChunkCardLinks: typeof import('./src/components/ChunkCardLinks.vue')['default']
    ChunkDetailPanel: typeof import('./src/components/ChunkDetailPanel.vue')['default']
    DrawerSidebar: typeof import('./src/components/DrawerSidebar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyCardGuide: typeof import('./src/components/EmptyCardGuide.vue')['default']
    KnowledgeUpload: typeof import('./src/components/KnowledgeUpload.vue')['default']
    MeshBackground: typeof import('./src/components/MeshBackground.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
